from node
#run npm config set proxy http://cache.univ-lille1.fr:3128
#run npm config set https-proxy http://cache.univ-lille1.fr:3128
run npm install -g grunt-cli 
workdir /usr/src/app
run mkdir /tmp/node_modules
run ln -s /tmp/node_modules /usr/src/app/node_modules
add package.json /usr/src/app
#run npm install
add . /usr/src/app
